esphome:
  name: alarm
  platform: ESP32
  board: esp32dev
  platformio_options:
    upload_speed: 460800
  includes:
    - stream_server.h
    - stream_server.cpp

external_components:
  - source: my_components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# Enable logging
logger:
  # level: VERBOSE
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

time:
  - platform: homeassistant
    id: homeassistant_time

text_sensor:
  - platform: version
    name: Alarm ESPHome Version
  - platform: wifi_info
    ip_address:
      name: Alarm IP
    ssid:
      name: Alarm SSID
    bssid:
      name: Alarm BSSID

sensor:
  - platform: uptime
    name: Alarm uptime

  - platform: wifi_signal
    name: Alarm WiFi Signal
    update_interval: 60s

switch:
  - platform: restart
    name: Alarm Restart

uart:
#  - id: uart0
#    tx_pin: GPIO1
#    rx_pin: GPIO3
#    baud_rate: 115200
#    data_bits: 8
#    parity: none
#    stop_bits: 1
  - id: uart1
    tx_pin: GPIO26
    rx_pin: GPIO27
    baud_rate: 9600
    data_bits: 8
    parity: none
    stop_bits: 1
  - id: uart2
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 19200
    data_bits: 8
    parity: none
    stop_bits: 2
  
custom_component:
  - lambda: |-
      auto stream_server1 = new StreamServerComponent(id(uart1),10000);
      return {stream_server1};
#  - lambda: |-
#      auto stream_server2 = new StreamServerComponent(id(uart2),10001);
#      return {stream_server2};

wintex:
  uart_id: uart2
  udl: "0000"

binary_sensor:
  - platform: "wintex"
    id: alarm_zone_01
    sensor_datapoint: 1
  - platform: "wintex"
    id: alarm_zone_02
    sensor_datapoint: 2
  - platform: "wintex"
    id: alarm_zone_03
    sensor_datapoint: 3
